version: '3.4'
services:
  node-server:
    container_name: node-server
    environment:
      - MONGO_DB_URI=mongodb://mongodb:27017/hubxCollection
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/opt/app/src
      - ./package.json:/opt/app/package.json
      - ./package-lock.json:/opt/app/package-lock.json
      - ./tsconfig.json:/opt/app/tsconfig.json
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
networks:
  app-network:
    driver: bridge
